/* Auto-generated by Growth Journey Analyser — Claude Code (CC credits) */
/* Last run: 2026-06-19 | Source: WhatsApp 14-day analysis | Messages: 501 */
/* Mary L. Pulamte excluded — manual scores preserved */
/* POD Leaders: Milind (A), Harsha (SA), Suman (AM), Nishi (AM) — leadership included */
window.AI_SCORES = {
  "Anam Imteyaz": {
    "skills": {
      "sales":22,"reporting":28,"maturity":38,"independence":28,
      "ai":8,"xfunc":22,"escalation":28,"comms":30,"enthusiasm":20
    },
    "leadership": { "people":0,"vision":0,"stakeholder":0,"developing":0,"resilience":0,"decision":0 },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.55,
    "flags": ["no_ai_adoption"]
  },
  "Chandel Yajat": {
    "skills": {
      "sales":28,"reporting":15,"maturity":32,"independence":30,
      "ai":8,"xfunc":18,"escalation":40,"comms":18,"enthusiasm":14
    },
    "leadership": { "people":0,"vision":0,"stakeholder":0,"developing":0,"resilience":0,"decision":0 },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.35,
    "flags": ["low_message_volume","active_escalation"]
  },
  "Suman Soumya Dash": {
    "skills": {
      "sales":38,"reporting":68,"maturity":58,"independence":55,
      "ai":15,"xfunc":62,"escalation":38,"comms":65,"enthusiasm":45
    },
    "leadership": {
      "people":38,"vision":30,"stakeholder":45,"developing":28,"resilience":50,"decision":42
    },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.70,
    "flags": ["attrition_risk","pod_leader"]
  },
  "Harsha Thomas John": {
    "skills": {
      "sales":55,"reporting":52,"maturity":55,"independence":50,
      "ai":15,"xfunc":38,"escalation":48,"comms":55,"enthusiasm":42
    },
    "leadership": {
      "people":28,"vision":22,"stakeholder":40,"developing":20,"resilience":45,"decision":42
    },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.65,
    "flags": ["pod_leader"]
  },
  "Kirubhavani B": {
    "skills": {
      "sales":42,"reporting":48,"maturity":52,"independence":35,
      "ai":8,"xfunc":35,"escalation":32,"comms":55,"enthusiasm":40
    },
    "leadership": { "people":0,"vision":0,"stakeholder":0,"developing":0,"resilience":0,"decision":0 },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.60,
    "flags": ["low_independence"]
  },
  "Nishi Agarwal": {
    "skills": {
      "sales":38,"reporting":45,"maturity":52,"independence":50,
      "ai":10,"xfunc":58,"escalation":30,"comms":52,"enthusiasm":45
    },
    "leadership": {
      "people":42,"vision":28,"stakeholder":45,"developing":30,"resilience":45,"decision":40
    },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.65,
    "flags": ["no_ai_adoption","pod_leader"]
  },
  "Milind Singh Bora": {
    "skills": {
      "sales":32,"reporting":42,"maturity":45,"independence":45,
      "ai":48,"xfunc":45,"escalation":35,"comms":42,"enthusiasm":52
    },
    "leadership": {
      "people":30,"vision":25,"stakeholder":32,"developing":22,"resilience":40,"decision":38
    },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.60,
    "flags": ["attrition_risk","ai_champion","pod_leader"]
  },
  "Priyanka Pati": {
    "skills": {
      "sales":28,"reporting":32,"maturity":42,"independence":35,
      "ai":8,"xfunc":22,"escalation":62,"comms":38,"enthusiasm":28
    },
    "leadership": { "people":0,"vision":0,"stakeholder":0,"developing":0,"resilience":0,"decision":0 },
    "last_updated": "2026-06-19",
    "sources": ["whatsapp"],
    "confidence": 0.45,
    "flags": ["chronic_escalation","low_visibility"]
  }
};
