"""
score_exporter.py — Exports AI scores to dashboard-consumable JavaScript

Writes:
  {dashboard_dir}/analyser/ai_scores.js       ← window.AI_SCORES object
  {dashboard_dir}/analyser/ai_scores_log.json ← full history log
"""

import json
import os
from datetime import datetime
from pathlib import Path


def export_scores(
    team_scores: dict,
    dashboard_dir: str,
    run_cost: float = 0.0,
    total_spent: float = 0.0,
) -> tuple[Path, Path]:
    """
    Export AI scores to ai_scores.js and ai_scores_log.json.

    Args:
        team_scores: {
            member_name: {
                skills:     { skill_key: int|None, ... },
                leadership: { ldr_key: int|None, ... },
                last_updated: 'YYYY-MM-DD',
                sources:    [str, ...],
                confidence: float,
            }
        }
        dashboard_dir: absolute path to the dashboard root
        run_cost:      cost of this specific run (USD)
        total_spent:   cumulative total spend (USD)

    Returns:
        (path_to_ai_scores_js, path_to_ai_scores_log_json)
    """
    output_dir = Path(dashboard_dir) / 'analyser'
    output_dir.mkdir(parents=True, exist_ok=True)

    js_path  = output_dir / 'ai_scores.js'
    log_path = output_dir / 'ai_scores_log.json'

    now_iso = datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
    today   = datetime.now().strftime('%Y-%m-%d')

    # ── Build JS object ──────────────────────────────────────────────────────
    # We serialize carefully to produce clean JS (not just json.dumps the whole thing)
    member_entries = []
    for name, data in sorted(team_scores.items()):
        skills    = data.get('skills', {})
        ldr       = data.get('leadership', {})
        last_upd  = data.get('last_updated', today)
        sources   = data.get('sources', [])
        confidence = data.get('confidence', 0.0)

        # Clean up None → null in JSON
        clean_skills = {k: v for k, v in skills.items()}
        clean_ldr    = {k: v for k, v in ldr.items()}

        entry = {
            'skills':       clean_skills,
            'leadership':   clean_ldr,
            'last_updated': last_upd,
            'sources':      sources,
            'confidence':   round(confidence, 3),
        }
        member_entries.append((name, entry))

    # Build the JS string
    inner_lines = []
    for name, entry in member_entries:
        json_str = json.dumps(entry, indent=4, ensure_ascii=False)
        # Indent the JSON value by 2 spaces for readability
        indented = '\n'.join('  ' + line if i > 0 else line for i, line in enumerate(json_str.split('\n')))
        inner_lines.append(f'  {json.dumps(name)}: {indented}')

    object_body = ',\n'.join(inner_lines)

    js_content = f"""/* Auto-generated by Growth Journey Analyser — do not edit manually */
/* Last run: {now_iso} | Cost this run: ${run_cost:.4f} | Total spent: ${total_spent:.4f} */
window.AI_SCORES = {{
{object_body}
}};
"""

    js_path.write_text(js_content, encoding='utf-8')

    # ── Update log JSON ──────────────────────────────────────────────────────
    log_entry = {
        'run_timestamp': now_iso,
        'run_cost_usd':  round(run_cost, 6),
        'total_spent_usd': round(total_spent, 6),
        'scores':        {name: entry for name, entry in member_entries},
    }

    history = []
    if log_path.exists():
        try:
            history = json.loads(log_path.read_text(encoding='utf-8'))
            if not isinstance(history, list):
                history = []
        except (json.JSONDecodeError, Exception):
            history = []

    history.append(log_entry)

    # Keep last 50 runs to avoid unbounded growth
    history = history[-50:]

    log_path.write_text(json.dumps(history, indent=2, ensure_ascii=False), encoding='utf-8')

    return js_path, log_path
